#******************************************************************************
# Copyright 2013, Qualcomm Innovation Center, Inc.
#
#    All rights reserved.
#    This file is licensed under the 3-clause BSD license in the NOTICE.txt
#    file for this project. A copy of the 3-clause BSD license is found at:
#
#        http://opensource.org/licenses/BSD-3-Clause. 
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the license is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the license for the specific language governing permissions and
#    limitations under the license.
#*****************************************************************************

Import('cpsenv')

srcs = cpsenv.Glob('*.cc')
srcs += cpsenv.Glob('Widgets/*.cc')
srcs += cpsenv.Glob('BusObjects/*.cc')

libs = []

# Static library
objs = cpsenv.Object(srcs)
libs.append(cpsenv.StaticLibrary('alljoyn_controlpanel', objs))

# Shared library
if cpsenv.get('LIBTYPE', 'static') != 'static':
    shobjs = cpsenv.SharedObject(srcs)
    libs.append(cpsenv.SharedLibrary('alljoyn_controlpanel', shobjs))

Return('libs')
