# Copyright 2013, Qualcomm Innovation Center, Inc.
#
#    All rights reserved.
#    This file is licensed under the 3-clause BSD license in the NOTICE.txt
#    file for this project. A copy of the 3-clause BSD license is found at:
#
#        http://opensource.org/licenses/BSD-3-Clause.
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the license is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the license for the specific language governing permissions and
#    limitations under the license.


ajtcl_root_default = '../../../../../ajtcl'
ajtcl_root = ARGUMENTS.get('AJ_TCL_ROOT', ajtcl_root_default)
env = SConscript(ajtcl_root + '/SConscript')

# we create a cloned ajtcl environment, so we don't taint ajtcl build with our defines and flags
iskoot_env = env.Clone()
Export('iskoot_env')
iskoot_env.SConscript('SConscript')
