# Copyright 2013, Qualcomm Innovation Center, Inc.
#
#    All rights reserved.
#    This file is licensed under the 3-clause BSD license in the NOTICE.txt
#    file for this project. A copy of the 3-clause BSD license is found at:
#
#        http://opensource.org/licenses/BSD-3-Clause. 
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the license is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the license for the specific language governing permissions and
#    limitations under the license.

Import('cpsenv')

if not cpsenv.has_key('_ALLJOYNCORE_'):
    cpsenv.Append(LIBS = ['alljoyn'])
    if cpsenv['BD'] == 'on' :
        bdFile = cpsenv.subst('$DISTDIR') + '/cpp/lib/BundledDaemon.o'
        cpsenv.Prepend(LIBS = [File(bdFile), 'ajdaemon'])    
    if cpsenv['OS'] == 'openwrt':
        cpsenv.AppendUnique(LIBS = [ 'stdc++', 'pthread' ])

cpsenv['CPS_DISTDIR'] = cpsenv['DISTDIR'] + '/controlpanel'

cpsenv.Install('$CPS_DISTDIR/inc/alljoyn/controlpanel', cpsenv.Glob('inc/alljoyn/controlpanel/*.h'))
cpsenv.Install('$CPS_DISTDIR/lib', cpsenv.SConscript('src/SConscript', exports = ['cpsenv']))
if cpsenv['BUILD_SERVICES_SAMPLES'] == 'on':
    cpsenv.Install('$CPS_DISTDIR/bin', cpsenv.SConscript('samples/SConscript', exports = ['cpsenv']))

# Build docs
installDocs = cpsenv.SConscript('docs/SConscript', exports = ['cpsenv'])
cpsenv.Depends(installDocs, cpsenv.Glob('$CPS_DISTDIR/inc/alljoyn/controlpanel/*.h'));
