# Copyright 2013, Qualcomm Innovation Center, Inc.
#
#    All rights reserved.
#    This file is licensed under the 3-clause BSD license in the NOTICE.txt
#    file for this project. A copy of the 3-clause BSD license is found at:
#
#        http://opensource.org/licenses/BSD-3-Clause. 
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the license is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the license for the specific language governing permissions and
#    limitations under the license.

Import('env')

# Dependent Projects
if not env.has_key('_ALLJOYNCORE_'):
    env.SConscript('../../../alljoyn_core/SConscript')
if not env.has_key('_ALLJOYN_ABOUT_'):
    env.SConscript('../../about/cpp/SConscript')

env['_ALLJOYN_CONTROLPANEL_'] = True

cpsenv = env.Clone()

cpsenv['CPS_DISTDIR'] = cpsenv['DISTDIR'] + '/services'

cpsenv.Append(LIBS = ['alljoyn_about'])

Export('cpsenv')

cpsenv.Append(CPPPATH = ['$CPS_DISTDIR/inc', 'inc'])
cpsenv.Append(LIBPATH = ['$CPS_DISTDIR/lib'])

cpsenv.VariantDir('$OBJDIR', 'src', duplicate = 0)
cpsenv.VariantDir('$OBJDIR/samples', 'samples', duplicate = 0)

headers = cpsenv.Install('$CPS_DISTDIR/inc/alljoyn/controlpanel', cpsenv.Glob('inc/alljoyn/controlpanel/*.h'))
libs = cpsenv.Install('$CPS_DISTDIR/lib', cpsenv.SConscript('$OBJDIR/SConscript'))
samples = cpsenv.Install('$CPS_DISTDIR/bin', cpsenv.SConscript('$OBJDIR/samples/SConscript'))

# Build docs
#installDocs = cpsenv.SConscript('docs/SConscript')
#cpsenv.Depends(installDocs, cpsenv.Glob('*.h'));

#returnValue = libs + samples + headers + installDocs
returnValue = libs + samples + headers
Return('returnValue')
