#*****************************************************************************
# Copyright 2013, Qualcomm Innovation Center, Inc.
#
#    All rights reserved.
#    This file is licensed under the 3-clause BSD license in the NOTICE.txt
#    file for this project. A copy of the 3-clause BSD license is found at:
#
#        http://opensource.org/licenses/BSD-3-Clause.
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the license is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the license for the specific language governing permissions and
#    limitations under the license.
#*****************************************************************************

Import('cps_env')

target_name = 'ControlPanelSample'

source_files = [
                Glob('*.c'),
                '../../src/CPSControllee/ControlPanelMain.c',
                ]

cps_env['CONTROLPANEL_DEFINE_STRING'] = 'CONTROLPANEL_SERVICE'
cps_env['INCLUDE_DIRS'] =  [
                     Dir('../../inc'),
                     Dir('inc'),
                 ]

cps_env.Append(CPPPATH = cps_env['INCLUDE_DIRS'])
cps_env.Append(CPPDEFINES = '$CONTROLPANEL_DEFINE_STRING')

local_objs = cps_env.Object(source_files)

Export('cps_env')
objs = cps_env.SConscript('../../src/CPSControllee/SConscript')
local_objs.append(objs)

# if we are called as part of services server sample, then return now:
if not cps_env.has_key('INDIV_BUILD'):
	Return('local_objs')

# we are called as part of ControlPanel build, which needs 
# server sample and About components
cps_env['SERSAMP_VARIANT_DIR'] = cps_env['CONTROLPANEL_DEFINE_STRING'].lower()
serversample_objs = cps_env.SConscript('$SERVERSAMPLE_ROOT_FROM_COMPONENT/SConscript', {'env': cps_env})

prog = cps_env.Program(target = target_name, 
			source = [
    			local_objs,
                serversample_objs,
                cps_env['aj_obj'],
			])
Return('prog')