#*****************************************************************************
# Copyright 2013, Qualcomm Innovation Center, Inc.
#
#    All rights reserved.
#    This file is licensed under the 3-clause BSD license in the NOTICE.txt
#    file for this project. A copy of the 3-clause BSD license is found at:
#
#        http://opensource.org/licenses/BSD-3-Clause.
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the license is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the license for the specific language governing permissions and
#    limitations under the license.
#*****************************************************************************

Import('controlpanel_env')

target_name = 'ControlPanelSample'

source_files = [
                Glob('*.c'),
                '../../src/CPSControllee/ControlPanelMain.c',
                ]

controlpanel_env.Append(CPPPATH = [
                                   Dir('../../inc'),
                                   Dir('inc'),
                                  ])

define_string = 'CONTROLPANEL_SERVICE'
controlpanel_env.Append(CPPDEFINES = [define_string])
local_objs = controlpanel_env.Object(source_files)

Export('controlpanel_env')
controlpanel_env.SConscript('../../src/CPSControllee/SConscript')
local_objs.append(controlpanel_env['cps_obj'])

# if we are called as part of services server sample, then
# add the service's DEFINE in the parent environment and return now:
if not controlpanel_env.has_key('INDIV_BUILD'):
	Return('local_objs')

# we are called as part of ControlPanel build, which needs 
# server sample and About components
controlpanel_env['SERSAMP_VARIANT_DIR'] = define_string.lower()
serversample_objs = controlpanel_env.SConscript('$SERVERSAMPLE_ROOT_FROM_COMPONENT/SConscript', {'env': controlpanel_env})

prog = controlpanel_env.Program(target = target_name, 
			source = [
    			local_objs,
                controlpanel_env['aj_obj'],
                serversample_objs,
			])

Return('prog')