# Copyright 2013, Qualcomm Innovation Center, Inc.
#
#    All rights reserved.
#    This file is licensed under the 3-clause BSD license in the NOTICE.txt
#    file for this project. A copy of the 3-clause BSD license is found at:
#
#        http://opensource.org/licenses/BSD-3-Clause.
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the license is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the license for the specific language governing permissions and
#    limitations under the license.

Import('cpsenv')

samples_env = cpsenv.Clone()

samples_env.Append(CPPPATH = samples_env.Dir('common').srcnode())
samples_env.Append(CPPPATH = samples_env.Dir('generated').srcnode())
#samples_env.Append(CPPDEFINES = 'USE_SAMPLE_LOGGER')
samples_env.Append(LIBS = ['alljoyn_controlpanel'])

cobjs = samples_env.SConscript('common/SConscript', {'env': samples_env})
genobjs = samples_env.SConscript('generated/SConscript', {'env': samples_env})

sample_dirs = [
    'ControlPanelSample'
    ]

returnValue = []
for sampleapp in sample_dirs:
    returnValue += samples_env.SConscript('%s/SConscript' % sampleapp, exports = { 'env': samples_env,
                                                                                   'cobjs': cobjs,
                                                                                   'genobjs' : genobjs })

Return('returnValue')
